/*Copyright (c) 2016-2017 profiles.com All Rights Reserved.
 This software is the confidential and proprietary information of profiles.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with profiles.com*/
package com.custom_profile_deploy.sales.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.custom_profile_deploy.sales.models.query.*;

public interface SalesQueryExecutorService {

    Page<SampleQResponse> executeSampleQ(Pageable pageable);

    void exportSampleQ(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}