/*Copyright (c) 2016-2017 profiles.com All Rights Reserved.
 This software is the confidential and proprietary information of profiles.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with profiles.com*/
package com.custom_profile_deploy.sales.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.runtime.data.model.QueryProcedureInput;

import com.custom_profile_deploy.sales.models.query.*;

@Service
public class SalesQueryExecutorServiceImpl implements SalesQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(SalesQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("salesWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "salesTransactionManager", readOnly = true)
    @Override
    public Page<SampleQResponse> executeSampleQ(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("sampleQ", params, SampleQResponse.class, pageable);
    }

    @Transactional(value = "salesTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportSampleQ(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput<SampleQResponse> queryInput = new QueryProcedureInput<>("sampleQ", params, SampleQResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

}